export const APP_USER = 'SERVICENOW_APP_USER';
export const APP_PASS = 'SERVICENOW_APP_PASSWORD';
export const INSTANCE_URL = 'SERVICENOW_APP_URL';
export const APP_CLIENT_ID = 'SERVICENOW_APP_CLIENT_ID';
export const APP_CLIENT_SECRET = 'SERVICENOW_APP_CLIENT_SECRET';
